language: java
jdk:
  - oraclejdk8
sudo: required
before_install:
    - sudo sh -c 'echo "deb http://sdkrepo.atlassian.com/debian/ stable contrib" >>/etc/apt/sources.list'
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B07804338C015B73
    - sudo apt-get update
    - sudo apt-get install atlassian-plugin-sdk
    - wget http://davidkoudela.cz/github/advanced-ldap-for-crucible/libs/sqljdbc4.jar  -O /tmp/sqljdbc4.jar
    - wget http://davidkoudela.cz/github/advanced-ldap-for-crucible/libs/sqljdbc41.jar -O /tmp/sqljdbc41.jar
install:
    - atlas-mvn install:install-file -Dfile=/tmp/sqljdbc4.jar  -Dpackaging=jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc4  -Dversion=4.0
    - atlas-mvn install:install-file -Dfile=/tmp/sqljdbc41.jar -Dpackaging=jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc41 -Dversion=4.1
script:
    - jdk_switcher use oraclejdk8
# Unit tests are part of the Integration tests.
# It is kept only for further test downgrade
#    - sudo atlas-unit-test
    - sudo atlas-integration-test
after_success:
# CREATE GIT TAG
  - git config --global user.email "ci-build@davidkoudela.cz"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=ci-build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
#  - git push --quiet https://$GITHUBKEY@github.com/dkoudela/advanced-ldap-for-crucible $GIT_TAG > /dev/null 2>&1
  - git push https://$GITHUBKEY@github.com/dkoudela/advanced-ldap-for-crucible $GIT_TAG
cache:
  directories:
    - $HOME/.m2
