language: java
sudo: required
before_install:
    - sudo sh -c 'echo "deb http://sdkrepo.atlassian.com/debian/ stable contrib" >>/etc/apt/sources.list'
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B07804338C015B73
    - sudo apt-get update
    - sudo apt-get install atlassian-plugin-sdk
script: "atlas-unit-test"
cache:
  directories:
    - $HOME/.m2
